xingyuhang:
  aliyun:
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket-name: yuhang-library-oss
      access-key-id: ${XINGYUHANG_ALIYUN_OSS_ACCESS_KEY_ID}
      access-key-secret: ${XINGYUHANG_ALIYUN_OSS_ACCESS_KEY_SECRET}
  baidu:
    audit:
      app-id: 7625072
      api-key: ${XINGYUHANG_BAIDU_AUDIT_API_KEY}
      secret-key: ${XINGYUHANG_BAIDU_AUDIT_SECRET_KEY}
server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: shop-user-service
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      port: 6379
      host: localhost
      password: root
      jedis:
        pool:
          min-idle: 10
          max-active: 10
  mvc:
    throw-exception-if-no-handler-found: false
  web:
    resources:
      add-mappings: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.cjc.controller

sms:
  aliyun:
    appcode: 82b0dccd264942039727ef95a00ca0c6
    # 国阳云配置
    sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
    template-id: 908e94ccf08b4476ba6c876d13f084ad
  verify-code:
    expire-minutes: 5